# -*- coding: utf-8 -*-
"""Main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HajTblqDLu5tyvRHnmLC9W5wPlESkTWj
"""

"""
At the command line, only need to run once to install the package via pip:

$ pip install google-generativeai
$ pip install ipywidgets

"""

from pathlib import Path
import hashlib
import google.generativeai as genai

genai.configure(api_key="AIzaSyAm_108FVUgFl_4lJO5Myr6iABb_J-QB_8")

# Inicializa modelo

generation_config = {
  "temperature": 0.3,
  "top_p": 1,
  "top_k": 32,
  "max_output_tokens": 3000,
}

safety_settings = [
  {
    "category": "HARM_CATEGORY_HARASSMENT",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
  {
    "category": "HARM_CATEGORY_HATE_SPEECH",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
  {
    "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
  {
    "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
]

model = genai.GenerativeModel(model_name="gemini-1.0-pro-vision-latest",
                              generation_config=generation_config,
                              safety_settings=safety_settings)

import ipywidgets as widgets
from IPython.display import display
from google.colab import drive

def get_file_name(change):
    global file_path
    file_path = None
    if upload_widget.value:
        file_name = list(upload_widget.value.keys())[0]
        file_contents = upload_widget.value[file_name]['content']

        # Save the file contents to a specific location
        file_path = f"/content/{file_name}"
        with open(file_path, "wb") as f:
            f.write(file_contents)

        print(f"Arquivo selecionado: {file_name} foi salvo em {file_path}")

    return file_path

# Criar widget de upload para arquivo imagem (input)

upload_widget = widgets.FileUpload(
    accept='*.jpg',  # Só arquivos JPG
    multiple=False  # Selecionar apenas uma imagem
)

# Criar botão
print("Por favor importe a foto do monumento ou local que você quer identificar:")
display(upload_widget)
print('\n\n')

# Chamar ação de salvar arquivo e trazer nome quando o usuário faz upload
upload_widget.observe(get_file_name, names='value')

# Retornar o caminho inteiro de onde o arquivo foi salvo
file_path = get_file_name(None)

# Enviar prompt

prompt_parts = [
  "Foto do local ",
  genai.upload_file("pisa.jpeg"),
  "Nome do local: Torre de pisa \n\n",
  "Descrição do local: A torre inclinada de Pisa, ou simplesmente Torre de Pisa, é um campanário da catedral da cidade italiana de Pisa. Está situada atrás da catedral, e é a terceira mais antiga estrutura na praça da Catedral de Pisa, depois da catedral e do baptistério. \n\nLocalizado em: Campo dei Miracoli\n\nEndereço: Piazza del Duomo, 56126 Pisa PI, Itália\n\nAltura: 57 m\nAndares: 8\nInauguração: 1372\nInício da construção: 9 de agosto de 1173\nHorário de funcionamento: Aberto ⋅ Fecha às 20:00\n\nArquitetos: Bonanno Pisano; Diotisalvi\nAbertura: 1373\nPeríodo de construção: 1174 (850 anos)",
  "Foto do local ",
  genai.upload_file("coliseu.jpeg"),
  "Nome do local: Coliseu \n\n",
  "Descrição do local: O Coliseu, originalmente conhecido como Anfiteatro Flaviano (em latim: Amphitheatrum Flavium; em italiano: Anfiteatro Flavio ou Colosseo), é um anfiteatro oval localizado no centro da cidade de Roma, capital da Itália. Construído com concreto e areia, é o maior anfiteatro já construído e está considerado uma das maiores obras da arquitetura e engenharia romanas.\n\nLocalizado em: Roma\n\nEndereço: Piazza del Colosseo, 1, 00184 Roma RM, Itália\n\nCapacidade: 80.000\n\nInauguração: 80 d.C.\nPeríodo de construção: 70 d.C.–80 d.C.\nAltura: 48 m\nEventos notáveis: Gladiatorial combat; Execuções públicas; Recriações de batalhas; Dramas mitológicos",
  "Foto do local: MASP",
  "Nome do local: MASP \n\n",
  "Descrição do local: Museu de Arte de São Paulo Assis Chateaubriand é um centro cultural e museu de arte brasileiro fundado em 1947 pelo empresário e jornalista paraibano Assis Chateaubriand. Entre os anos de 1947 e 1990, o crítico e marchand italiano Pietro Bardi assumiu a direção do MASP a convite de Chateaubriand.\n\nEndereço: Av. Paulista, 1578 - Bela Vista, São Paulo - SP, 01310-200\n\nArquiteta: Lina Bo Bardi\nHorário de funcionamento: Aberto ⋅ Fecha às 18:00\n\nVisitantes: 729 325 (2019)\nEstilos arquitetônicos: Arquitetura moderna, Arquitetura brutalista\n\nFundação: 1947\n\nInauguração: 1947 (77 anos)\n\nTelefone: (11) 3149-5959\n\nPresidente(a): Heitor Martins\n\nTipo: museu de arte, centro cultural, património histórico",
  "Foto do local ",
  genai.upload_file("bolivia.jpg"),
  "Nome do local: Igreja de São Francisco \n\n",
  "Descrição do local: A igreja de São Francisco é uma igreja barroca localizada na cidade de La Paz, Bolívia. É um dos marcos mais importantes da cidade e um dos principais destinos turísticos.\n\nEndereço: Calle Potosí, La Paz, Bolívia\n\nArquiteto: Fray Francisco de San José\nEstilo arquitetônico: Barroco\nCulto: Católico Romano\nAbertura: 1784",
  "Foto do local ",
  genai.upload_file(file_path),
  "Nome do local: ",
]

response = model.generate_content(prompt_parts)
print("Legal! Nós identificamos o seguinte local pela foto que você enviou: \n\n")
print(response.text)